import { VideoItem } from './types';

export const INITIAL_SEED_VIDEOS: VideoItem[] = [
  {
    id: 'soul-land-ep1',
    title: 'Awakening of the Twin Martial Souls',
    donghuaName: 'Soul Land (Douluo Dalu)',
    description: 'Tang San, after reincarnating into the Douluo Continent, undergoes the martial soul awakening ceremony in Holy Spirit Village and awakens the legendary Blue Silver Grass alongside the Clear Sky Hammer.',
    episodeNumber: 1,
    seasonNumber: 1,
    thumbnailUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1000&auto=format&fit=crop&q=80',
    videoStoragePath: 'videos/soul-land/ep1.mp4',
    videoStreamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    accessType: 'free',
    requiredPlan: 'basic',
    duration: '22:45',
    category: 'Xianxia',
    genre: 'Cultivation',
    language: 'Hindi / English Sub',
    subtitles: 'Hindi, English, Chinese',
    tags: ['Cultivation', 'Martial Souls', 'Reincarnation', 'Tang San'],
    published: true,
    views: 184200,
    likes: 14200,
    rightsStatus: 'Licensed Distributor India',
    licenseInfo: 'Decent Animation Official Streaming Rights 2026-2028',
    territory: 'IN, SAARC',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'btth-three-year-agreement',
    title: 'The Nalan Clan Trial: The Three-Year Promise Fulfilled',
    donghuaName: 'Battle Through the Heavens (Doupo Cangqiong)',
    description: 'Xiao Yan ascends the Misty Cloud Sect mountain stairs to fulfill the legendary three-year promise against Nalan Yanran. Flaming lotus cultivation powers clash in a breathtaking showdown.',
    episodeNumber: 12,
    seasonNumber: 4,
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1000&auto=format&fit=crop&q=80',
    videoStoragePath: 'videos/btth/season4-ep12.mp4',
    videoStreamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    accessType: 'subscription',
    requiredPlan: 'basic',
    duration: '24:10',
    category: 'Cultivation',
    genre: 'Action',
    language: 'Hindi Dub',
    subtitles: 'English, Hindi',
    tags: ['Xiao Yan', 'Heavenly Flame', 'Misty Cloud Sect', 'Martial Arts'],
    published: true,
    views: 312000,
    likes: 29500,
    rightsStatus: 'Licensed Distribution',
    licenseInfo: 'Exclusive SAARC Regional Audio Dub Rights',
    territory: 'India, Nepal, Bangladesh',
    createdAt: '2026-02-01T12:00:00Z',
  },
  {
    id: 'renegade-immortal-ep24',
    title: 'Ancient God Domain: Blood Slaughter Domain',
    donghuaName: 'Renegade Immortal (Xian Ni)',
    description: 'Wang Lin steps into the treacherous Sea of Devils. Relying on sheer determination and his ruthless Ji Realm divine sense, he carves an unforgiving path towards genuine godhood.',
    episodeNumber: 24,
    seasonNumber: 1,
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1000&auto=format&fit=crop&q=80',
    videoStoragePath: 'videos/renegade-immortal/ep24.mp4',
    videoStreamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    accessType: 'exclusive',
    requiredPlan: 'premium',
    duration: '21:30',
    category: 'Xianxia',
    genre: 'Martial Arts',
    language: 'Hindi / English Sub',
    subtitles: 'English, Hindi',
    tags: ['Wang Lin', 'Ji Realm', 'Ruthless MC', 'Cultivation'],
    published: true,
    views: 94800,
    likes: 11200,
    rightsStatus: 'Licensed Studio Direct',
    licenseInfo: 'Digital Distribution Contract No. DA-2026-XN',
    territory: 'Worldwide Ex-China',
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'shrouding-the-heavens-vip',
    title: 'Nine Dragons Pulling Coffin: Cosmic Transit',
    donghuaName: 'Shrouding the Heavens (Zhe Tian)',
    description: 'Bronze dragons drag an ancient cosmic coffin across the stars crashing onto Mount Tai. Ye Fan and his classmates embark onto the Big Dipper constellation into a primordial dao epoch.',
    episodeNumber: 1,
    seasonNumber: 1,
    thumbnailUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1000&auto=format&fit=crop&q=80',
    videoStoragePath: 'videos/shrouding-heavens/ep1.mp4',
    videoStreamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    accessType: 'vip',
    requiredPlan: 'vip',
    duration: '26:00',
    category: 'Fantasy',
    genre: 'Cultivation',
    language: 'Hindi Dub',
    subtitles: 'Hindi, English',
    tags: ['Nine Dragons', 'Ye Fan', 'Cosmic Xianxia', 'Ancient Artifacts'],
    published: true,
    views: 45000,
    likes: 8100,
    rightsStatus: 'VIP Exclusive First-Window',
    licenseInfo: 'Early Access Window DA-VIP-2026',
    territory: 'India',
    createdAt: '2026-03-10T14:00:00Z',
  },
  {
    id: 'perfect-world-ep132',
    title: 'Imperial Pass Siege: Heavenly Sovereign Clashes',
    donghuaName: 'Perfect World (Wanmei Shijie)',
    description: 'Shi Hao stands tall with the Willow Deity willow branch against primordial giants on the ancient desolate battlefield. One person defends an entire kingdom from desolation.',
    episodeNumber: 132,
    seasonNumber: 3,
    thumbnailUrl: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?w=1000&auto=format&fit=crop&q=80',
    videoStoragePath: 'videos/perfect-world/ep132.mp4',
    videoStreamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    accessType: 'subscription',
    requiredPlan: 'basic',
    duration: '23:15',
    category: 'Action',
    genre: 'Fantasy',
    language: 'Hindi / English Sub',
    subtitles: 'Hindi, English',
    tags: ['Shi Hao', 'Willow Deity', 'Primordial Treasure', 'Gods Battle'],
    published: true,
    views: 245000,
    likes: 21900,
    rightsStatus: 'Licensed Distribution',
    licenseInfo: 'Season 3 Broadcast License',
    territory: 'Worldwide',
    createdAt: '2026-03-14T09:30:00Z',
  },
  {
    id: 'a-will-eternal-ep1',
    title: 'Stealing the Spirit Chicken: Bai Xiaochun Descends',
    donghuaName: 'A Will Eternal (Yi Nian Yong Heng)',
    description: 'Fearful of death, young Bai Xiaochun lights the incense stick again and again hoping for immortal favor, ending up at the Spirit Stream Sect cooking stoves.',
    episodeNumber: 1,
    seasonNumber: 1,
    thumbnailUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1000&auto=format&fit=crop&q=80',
    videoStoragePath: 'videos/a-will-eternal/ep1.mp4',
    videoStreamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    accessType: 'free',
    requiredPlan: 'basic',
    duration: '19:50',
    category: 'Comedy',
    genre: 'Adventure',
    language: 'Hindi Dub',
    subtitles: 'Hindi, English',
    tags: ['Bai Xiaochun', 'Spirit Stream', 'Comedy', 'Cultivation'],
    published: true,
    views: 168000,
    likes: 18500,
    rightsStatus: 'Licensed Free Tier',
    licenseInfo: 'Public Promotional Tier License',
    territory: 'India',
    createdAt: '2026-03-16T11:00:00Z',
  }
];
